### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by ardelldio** [gedelumbung/simpeg#1]
Waktu username dan password dimasukkan muncul error: Object not found

**Comment by nexarioapp** [comment]
itu masalah file .htaccess yang tidak tersedia, buat file .htaccess di root folder isikan seperti berikut
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L] 
</IfModule>

**Comment by sarolangun** [comment]
Itu file dlm bentuk txt yah

**Comment by sarolangun** [comment]
Sudah saya tambahkan file .htaccess dlm bentuk file txt
Tp hasil masih sama

**Comment by sarolangun** [comment]
Buat app setengah hati

Makasi min
